### ISSUE TITLE
MacOS application bundle? 

### ISSUE THREAD

**Issue by fladd** [wereturtle/ghostwriter#368]
The installation instructions say that I can download a Marcos application bundle. It does not mention,  however,  where I can download this from.

**Comment by pazos** [comment]
@fladd: sorry, I updated the readme but forgot to update the app/dmg file. 

I uploaded a DMG to MEGA because I have no write access to this repo. Please note that this is built by me and not by @wereturtle.

https://mega.nz/#!DnoRgbRI!OJ7FaK315Gq0ZByWde0L3EFqsTqf8oLfdmGUbHmqAiI

Also, please notice that the README will give you an app built agaisnt qt 5.5.1 (the last with official qtwebkit support) and this build is against Qt 5.10.1 and annulen qtwebkit fork.

You'll notice some bugs related to HUD positioning on macOS native fullscreen. I'm aware of those. Please report any other bug you'll find.

**Comment by tommyboylab** [comment]
@pazos  Thank you once again! Been using Ghostwriter on Linux for a while and haven't found a better text editor now moving to my Corporate Macbook. Happen to have a build of the latest version (1.7.3?) I'm still unable to compile it myself on Mojave.
